trigger:
- main

resources:
  pipelines:
  - pipeline: SecondPipeline
    source: cleverpine.homebrew-booty
    trigger:
      branches:
        - cicd

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Extracting the version number from the config.sh file
    VERSION_LINE=$(sed -n '2p' ./config.sh)
    APP_VERSION=$(echo $VERSION_LINE | cut -d '"' -f 2)
    echo $APP_VERSION > appVersion.txt
    echo "##vso[task.setvariable variable=appVersion]$APP_VERSION"
  displayName: 'Extract App Version'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-dobry-serviceconnection'
    repositoryName: 'cleverpine/Booty'
    action: 'create'
    tagSource: 'userSpecifiedTag'
    tag: '$(appVersion)'
    releaseTitle: 'Release $(appVersion)'

- publish: $(System.DefaultWorkingDirectory)
  artifact: appVersionArtifact
  displayName: 'Publish appVersion Artifact'

